# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

install:
  - npm install cordova
  - npm install
  - npm link

build: off

test_script:
  - node --version
  - npm --version
  - echo y | android update sdk -u --filter android-27
  - npm run test-appveyor
