# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: iOS Testsuite

on: [push, pull_request]

jobs:
  test:
    name: iOS ${{ matrix.versions.ios }} Test
    runs-on: macos-latest

    # hoist configurations to top that are expected to be updated
    env:
      node-version: 16
      platform: 'ios'

    # configurations for each testing strategy (test matrix)
    strategy:
      matrix:
        versions:
          - ios: 12
            xcode: 11.7

          - ios: 13
            xcode: 11.7

          - ios: 14
            xcode: 12.5.1

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: ${{ matrix.versions.xcode }}

      - name: Run Environment Information
        run: |
          node --version
          npm --version
          xcodebuild -version

      - name: Run npm install
        run: |
          npm i -g cordova ios-deploy
          npm ci

      - name: Run paramedic tests
        run: node main.js --config ./pr/local/${{ env.platform }}-${{ matrix.versions.ios }}.x.config.json  --plugin ./spec/testable-plugin/
